[global]
namespace = "kafka"
kafka_version = "2.6.2"

sasl_enabled = false
sasl_handshake = true
sasl_username = ""
sasl_password = ""
sasl_mechanism = ""
sasl_service_name = ""
sasl_kerberos_config_path = ""
sasl_realm = ""
sasl_keytab_path = ""
sasl_kerberos_auth_type = ""
sasl_disable_PA_FX_FAST = false

tls_enabled = false
tls_server_name = ""
tls_ca_file = ""
tls_cert_file = ""
tls_key_file = ""
tls_insecure_skip_tls_verify = false

topic_filter = ".*"
topic_exclude = "^$"
group_filter = ".*"
group_exclude = "^$"

use_consume_lag_zookeeper = false
zookeeper_servers = [""]

offset_show_all = true
concurrent_enable = false
topic_works = 100
