[global]
username = "elastic"
password = "123456"

es_timeout="5s"
es_all_nodes=false
es_node=""
es_export_indices=false
es_export_indices_settings=false
es_export_indices_mappings=false
es_export_index_aliases=true
es_export_ilm=""
es_export_shards=false
es_export_slm=false
es_export_data_stream=false
es_cluster_info_interval="5m"
es_ca=""
es_client_private_key=""
es_client_cert=""
es_insecure_skip_verify=false
